### ISSUE TITLE
Support for Extended-Max-Requested-BW-DL and Extended-Max-Requested-BW-UL AVP AVP in freediameter

### ISSUE THREAD

**Issue by asreek** [omec-project/freediameter#15]
Currently freediameter uses version 14.3.0. This does not have support for below AVPs(defined in 29.214) required for 5G NSA support.
Extended-Max-Requested-BW-DL AVP
Extended-Max-Requested-BW-UL AVP

Please do the needful.

**Comment by clstefi** [comment]
The details of "Extended-Max-Requested-BW-DL AVP" and "Extended-Max-Requested-BW-UL AVP" can be found in the **3GPP Spec 29.214 version 15.6.0 - sections 5.3.52 and 5.3.53** respectively.

**Comment by clstefi** [comment]
NSA Support requires the AMBR AVP to be updated in the format specified in the **Spec 29.272 v15.6.0 - section 7.3.41**. 

PFB the AVP format.
 AMBR ::= <AVP header: 1435 10415>
{ Max-Requested-Bandwidth-UL }
{ Max-Requested-Bandwidth-DL }
[ Extended-Max-Requested-BW-UL ]
[ Extended-Max-Requested-BW-DL ]
*[AVP]

**Comment by brianwaters3** [comment]
Untar the attached tar into the freediameter/extensions directory and rebuild freediameter.

29.214 - defines Extended-Max-Requested-BW-UL and Extended-Max-Requested-BW-DL
29.272 - adds Extended-Max-Requested-BW-UL and Extended-Max-Requested-BW-DL to the AMBR grouped AVP.

[Extended-Max-Requested-BW.tar.gz](https://github.com/omec-project/freediameter/files/4753152/Extended-Max-Requested-BW.tar.gz)
