### ISSUE TITLE
Install issue - A required package was not found on Ubuntu

### ISSUE THREAD

**Issue by JosmaM** [omec-project/freediameter#5]
Hi,

I'm trying to install it on Ubuntu 
Description: Ubuntu 16.04.6 LTS
Release: 16.04
Codename: xenial

While trying to compile the package with cmake ../freeDiameter (All on ON)
I get this error. I don't know what package is missing.

/fDbuild# cmake ../freeDiameter/
-- Checking for module 'jsoncpp'
--   No package 'jsoncpp' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  extensions/dict_json/CMakeLists.txt:7 (PKG_CHECK_MODULES)

**Comment by krsna1729** [comment]
I am not sure if this was ever used on its own. https://github.com/omec-project/c3po and https://github.com/omec-project/openmme have used this repo as dependencies.

cc @lbertz02 @brianwaters3
